### ISSUE TITLE
Not showing topic section on preview

### ISSUE THREAD

**Issue by 3clypse** [bump-sh/bump-cli#18]
Hey!
I tried to validate & preview the example from [here](https://github.com/bump-sh/bump-ci-example/blob/master/bump.openapi.v3.yml)
using: `bump preview bump.openapi.v3.yml --specification openapi/v3/yaml` but the generated preview doesn't show the content of `x-sections:`

You can see the preview below:
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/11727815/80959466-2717ae00-8e07-11ea-8205-2c996dc7ffea.png">

Am I doing something wrong? 🤔 

Thanks in advance!

**Comment by scharrier** [comment]
Hi @3clypse, thanks for your message. You're right, and it's because we have never updated this example file!

We have updated this property name, it's now `x-topics`. You will find more details here: https://help.bump.sh/openapi-support#adding-topics-to-your-documentation

Sorry for this, we'll fix the example file in a few minutes.

**Comment by scharrier** [comment]
We have updated the [example here](https://github.com/bump-sh/bump-ci-example/blob/master/bump.openapi.v3.yml). It should be OK now. I fix this issue, feel free to re-open it if needed.

**Comment by 3clypse** [comment]
It works like a charm.

Thanks so much for the solution and quick reply!! :)

**Comment by scharrier** [comment]
You're welcome, glad to help!
